### ISSUE TITLE
Ultrahook

### ISSUE THREAD

**Issue by ap1969** [anderspitman/awesome-tunneling#10]
Hi,
Another useful one: Ultrahook (runs on Ruby) offers a free fixed-subdomain option, so a good free alternative to ngrok.

EDIT: It only forwards HTTP POST requests, so not the same as ngrok. But still useful in testing webhooks, as it's name suggests.

Hope that helps,
Andy

**Comment by anderspitman** [comment]
Thanks for the submission @ap1969. This list is more focused on tools for self-hosting, so I think Ultrahooks is a little narrow as it only supports webhooks.
