### ISSUE TITLE
Add LocalCan app - ngrok alternative

### ISSUE THREAD

**Issue by Jaarson** [anderspitman/awesome-tunneling#117]
[LocalCan.com](https://www.localcan.com/) is macOS app and Ngrok alternative without monthly subscription - see [Ngrok vs. LocalCan](https://www.localcan.com/ngrok-alternative)

**Comment by woshichenghaibo** [comment]
expensive

**Comment by Jaarson** [comment]
It's much cheaper than ngrok. Have you seen the pricing comparison table from the link?

**Comment by anderspitman** [comment]
Hi @Jaarson, thanks for the addition! What is your business plan if people start abusing your one-time payment to send more data than you can afford to transfer for $47?

**Comment by Jaarson** [comment]
I have plenty of transfer quota, and I'm closely monitoring transfer per user account, per month. I think it's unlikely to exceed it, but then I can introduce a monthly cap with an option to buy additional transfer for most demanding users.

**Comment by Jaarson** [comment]
Hi @anderspitman, any chances for including LocalCan in awesome-tunneling list? 🙏

**Comment by anderspitman** [comment]
Yeah we'll get it in. I tend to do these in batches as I make time. If you make a good PR for me it's much more likely to get in quickly. Just follow the format and don't sound too much like an ad.

**Comment by Jaarson** [comment]
Thanks @anderspitman, PR is ready 👍

**Comment by anderspitman** [comment]
Fixed in #142
