### ISSUE TITLE
Add List of cross-compatible programs

### ISSUE THREAD

**Issue by KuraakaiGoro** [anderspitman/awesome-tunneling#123]
Some of the tunneling software on this list I've used, but could never connect to Windows from Linux, and vice versa. I want to know what programs are cross-compatible so my friends can connect to me. For example, out of these programs, I've tried Zerotier and ngrok. Though they can be ran on both Linux and Windows, they can't connect to each other

**Comment by anderspitman** [comment]
You're saying a client running on Windows can't connect to a server running Linux? That's surprising. If it runs at all I would expect it to work. Are you sure the windows firewall wasn't blocking it?

**Comment by KuraakaiGoro** [comment]
> You're saying a client running on Windows can't connect to a server running Linux? That's surprising. If it runs at all I would expect it to work. Are you sure the windows firewall wasn't blocking it?

Could be the problem, I never thought to ask if they had a firewall on. Next time I'll try and see if that's the issue.
