### ISSUE TITLE
please add gost 

### ISSUE THREAD

**Issue by woodlyer** [anderspitman/awesome-tunneling#126]
gost is "A simple security tunnel written in golang"  
project url:  https://github.com/go-gost/gost  

gost is very powerful.   
tunnel can be build over socks5, tls, kcp, quic.... many many protocol.  

documents is at:  https://latest.gost.run/en/tutorials/reverse-proxy-tunnel/

**Comment by anderspitman** [comment]
Thanks for the solid suggestion @woodlyer! I've added gost to the list.
