### ISSUE TITLE
Build your own tunnel

### ISSUE THREAD

**Issue by 0xdade** [anderspitman/awesome-tunneling#144]
I'm just sharing this here because a handful of people are telling me about your list in response to my recent post about building my own tunnel solution.

I guess what differentiates my article is that there's nothing to install, really. It's a bash function on the client, a couple bash conditionals on the server, and an nginx server block. It's limited to HTTPS only (but I think could be modified to work for arbitrary TCP tunnels, just wasn't what I was after).

Love that there are so many other people excited about tunneling solutions and their wide variety of uses.

https://0xda.de/blog/2024/04/can-you-grok-it/

**Comment by anderspitman** [comment]
Thanks @0xdade! I added your blog post to the references section in commit [4036304](https://github.com/anderspitman/awesome-tunneling/commit/40363048402c40434c3fe367e19e8f8857149dda)
