### ISSUE TITLE
boringproxy needs ssh

### ISSUE THREAD

**Issue by alfem** [anderspitman/awesome-tunneling#18]
After some unsuccessful testing, I noticed boringproxy needs an ssh connection. So it does not work in private firewall protected networks allowing only http traffic

**Comment by Oujiii** [comment]
This issue needs to be posted on: https://github.com/boringproxy/boringproxy/issues

**Comment by anderspitman** [comment]
@Oujiii is correct. Feel free to open an issue on the boringproxy page.
