### ISSUE TITLE
Add teleport

### ISSUE THREAD

**Issue by luisdavim** [anderspitman/awesome-tunneling#19]
I think https://github.com/gravitational/teleport would also be relevant to this list.

**Comment by anderspitman** [comment]
Hey @luisdavim, sorry for the long delay. Teleconsole is already on the list. A quick glance doesn't make it obvious what the difference is. Do you happen to know?

**Comment by anderspitman** [comment]
Hm well for one thing it looks like Teleconsole has been shut down.

**Comment by anderspitman** [comment]
I went ahead and replaced teleconsole with Teleport.
