### ISSUE TITLE
Remove lynk.sh

### ISSUE THREAD

**Issue by anderspitman** [anderspitman/awesome-tunneling#23]
lynk.sh now redirects to "Loophole Labs". I poked around a bit and wasn't able to see any mention of a tunneling solution. @Jspsun @ShivanshVij is there any reason you feel I should leave it on the list?

**Comment by dionperera** [comment]
read this: [](https://loopholelabs.io/docs/frisbee/introduction)

**Comment by dionperera** [comment]
read this: https://loopholelabs.io/docs/frisbee/introduction

**Comment by ShivanshVij** [comment]
Hey all! We're actually about to re-release Lynk in a few days, completely open source and overhauled for a significant speed boost (only 2ms latency added by the tunnel). You're welcome to remove this right now and we'll open a new issue to add it back when we're ready. Our expected launch date for the open-source version is Sept. 18 or earlier.

**Comment by mrbluecoat** [comment]
@ShivanshVij was Lynk rebranded to Frisbee? Lynk.sh redirects me to Loophole Labs and your GitHub site only lists Frisbee and the archived Parasite project (p.s. parasite.sh domain appears to be down)

**Comment by anderspitman** [comment]
@ShivanshVij any update on this?

**Comment by anderspitman** [comment]
I'm gonna go ahead and remove lynk.sh for now.
