### ISSUE TITLE
Inlets is not open source

### ISSUE THREAD

**Issue by sagikazarmark** [anderspitman/awesome-tunneling#25]
The open source version of inlets became inlets pro as far as I understand. There are some open source components, but I don't think you can use those without a subscription.

**Comment by anderspitman** [comment]
@alexellis can you confirm the open source status of inlets?

**Comment by alexellis** [comment]
We have a mix of open source and subscription components for inlets. Why are you asking the question? Do you want me to update a description for you?

**Comment by sagikazarmark** [comment]
I believe that would make sense. Although it has open source components, it's not really open source in the sense that you can't do whatever you want without a subscription (I'm not even sure one can use it without one). I believe that makes it rather a commercial solution than a real open source project.

**Comment by anderspitman** [comment]
I would say if it's relatively straight-forward to self-host a tunneling solution using Inlets using only open source code, and we can update the entry to point to documentation of how to do that, that would be great. Otherwise we should move it to the commercial section.

**Comment by anderspitman** [comment]
Given that the originally-linked repo is now archived, and a bit more research, it seems pretty clear inlets is now primarily commercial software. I'll go ahead and move it and change the link to the home page rather than the GitHub repo.

**Comment by anderspitman** [comment]
@alexellis feel free to comment here if you think this is an inaccurate assessment.

**Comment by alexellis** [comment]
I would rather you just used the description from the website or docs.

**Comment by anderspitman** [comment]
Which one specifically? The point of this list is to compare different tunneling solutions. Most of the copy on the inlets site makes similar claims to other projects. Tight integration with Kubernetes is the most obvious differentiator I see. If there are others please point them out.
