### ISSUE TITLE
Add `rathole`

### ISSUE THREAD

**Issue by rapiz1** [anderspitman/awesome-tunneling#29]
I developed [rathole](https://github.com/rapiz1/rathole) - A secure, stable and high-performance reverse proxy for NAT traversal, written in Rust. Benchmark shows that it has some advantages on the performance and memory consumption.

There's not much Rust stuff on the list. I hope `rathole` could be a good addition :)

**Comment by anderspitman** [comment]
Looks great! So many of these tools don't really seem to explain why they were created rather than using/improving something that already existed. Nice to see one with specific goals and differentiation. Went ahead and added it.

I have a few questions for my own curiosity, and perhaps so I can improve the entry:

1. What motivated you to create rathole? Were you using frp and not getting the performance you needed? Just for fun? Learning rust?
2. What method do you use under the hood for tunneling? Based on a quick glance at the issues it looks like you're using a single TCP socket? Are you using a library for multiplexing or doing a custom protocol (or maybe copying whatever frp does)?

Thanks!

**Comment by rapiz1** [comment]
Thanks! Glad to hear that.

1. I heard people complaining about performance and resource consumption of frp. The latter is more problematic on routers. Also some guys are concerned about the security model of frp, where the server fully trusts clients to open any ports of the server. What's worse is that by default there isn't any authentication. In addition, frp tries to put too much things in it, making itself like a mixture of nat traverser, nginx and VPN. Personally I prefer the unix philosophy of "Make each program do one thing well".
2. Only a UDP service will be forwarded via a single TCP socket because I'm still on the fence about some design decisions and plan to improve it in the future. For TCP services, there's a TCP connection for each of visitors. Generally speaking, the tunnel method of rathole is quite like frp, but with a more compact protocol and carefully avoiding unnecessary copying/serialization.

**Comment by anderspitman** [comment]
Right on. I love the idea of a tunneling server tuned for router hardware. That could be really important in the coming years.

I'm planning on designing a new tunneling protocol for [boringproxy](https://boringproxy.io/). Currently it uses HTTPS for coordination but SSH for the tunnels. I want to reduce it down to just operating on the HTTPS ports, and potentially switch to a UDP-based protocol like QUIC to get rid of head-of-line blocking. The actual method is less important than the fact that we need an open protocol that multiple projects can implement, so we get interoperability. If you're interested in collaborating on the design let me know.

PS - congrats on the traction of rathole! I keep having to edit the list (which is sorted by GH stars) to move it up. Do you know where most of your traffic is coming from?

**Comment by rapiz1** [comment]
> The actual method is less important than wanting to have an open protocol that multiple projects can implement, so we get interoperability. If you're interested in collaborating on the design let me know.

Cool. But I have no idea about how will such a protocol look like. Do you have a prototype so I can know how to help?

> Do you know where most of your traffic is coming from?

I post it on a local forum of my region, where people use `frp` a lot because NAT and firewalls are pervasive and it's hard to get a public IP. I'm not too surprised that people have a passion for this kind of tool. After the "bootstrap", there seems also a lot of traffic from GitHub itself.

**Comment by anderspitman** [comment]
Hey sorry for the delay, We've started a conversation about the protocol over on the IndieBits forums if you want to join us:

https://forum.indiebits.io/t/toward-an-open-tunneling-protocol/30/2
