### ISSUE TITLE
Do any of these offer free domain usage like ngrok does?

### ISSUE THREAD

**Issue by e-t-l** [anderspitman/awesome-tunneling#49]
I know this list is focused on self-hosting, but do _any_ of the options offer free assigned URLs in case the user doesn't have their own domain registered?

**Comment by anderspitman** [comment]
I'm pretty sure several in the [commercial section](https://github.com/anderspitman/awesome-tunneling#commercialclosed-source) do.

**Comment by e-t-l** [comment]
Thanks, I didn't see that section. I like FOSS/freemium-open source when possible, so Cloudflare Tunnel and Loophole both look like good options!

**Comment by anderspitman** [comment]
For sure. Cloudflare Tunnel is what I recommend to most people.
