### ISSUE TITLE
Consider https://github.com/openziti/ziti

### ISSUE THREAD

**Issue by dovholuknf** [anderspitman/awesome-tunneling#50]
I think you'd be happy with the project. I'm a dev on it - and i'd be happy to meet with you. I'd be happy to have you on ziti tv too if yoo wanted? :) a weekly livestream we do - generally about ziti but we could do a podcast sorta thing. 

close this if i'm outta line :)

https://github.com/openziti/ziti

**Comment by dovholuknf** [comment]
put a pr up: https://github.com/anderspitman/awesome-tunneling/pull/51

**Comment by anderspitman** [comment]
Added
