### ISSUE TITLE
Inlets open source link leads to 404

### ISSUE THREAD

**Issue by ssddanbrown** [anderspitman/awesome-tunneling#53]
The "open source" link  found on this line:

https://github.com/anderspitman/awesome-tunneling/blob/710bf1e051dabc42e2be1f08f3f2ab42121af57f/README.md?plain=1#L85

leads to a non-existing repo. I believe the maintainer removed any official repos of the original open source code-base in early January of this year. 

I did upload a detached fork of the code to my own GitHub account to retain for those that needed it:
https://github.com/ssddanbrown/inlets
This had the latest original commit history I could find at time of creation. 

I didn't create a PR as wasn't sure if you'd want to link to a non-official repo or if you'd rather just remove the link.

**Comment by anderspitman** [comment]
Thanks @ssddanbrown. I believe this is corrected in the current version.
