### ISSUE TITLE
Tailscale now uses a BSD 3-clause license with a separate PATENTS file

### ISSUE THREAD

**Issue by troyjfarrell** [anderspitman/awesome-tunneling#6]
Please consider updating Tailscale's entry to note the BSD license and PATENTS file:

https://github.com/tailscale/tailscale/blob/main/LICENSE
https://github.com/tailscale/tailscale/blob/main/PATENTS

**Comment by anderspitman** [comment]
Thanks @troyjfarrell. Would this be an accurate description of the current state of tailscale?:

BSD3+patents client. Server is closed.

**Comment by troyjfarrell** [comment]
That sounds accurate to me based upon what I see in their git repository.  If any of the Tailscale folks–@bradfitz is the most prolific–think I'm wrong, they can correct me.
