### ISSUE TITLE
Please add srv.us

### ISSUE THREAD

**Issue by pcarrier** [anderspitman/awesome-tunneling#62]
Would very much appreciate getting https://srv.us on the list.

**Comment by pcarrier** [comment]
No news?

**Comment by anderspitman** [comment]
Hi @pcarrier, sorry for the delay. Generally these get in a lot faster if you submit a PR, but I'm a bit behind on those as well. srv.us looks pretty simple though, so if you submit a PR I can try to get it merged quickly.
