### ISSUE TITLE
just iptables?

### ISSUE THREAD

**Issue by markuman** [anderspitman/awesome-tunneling#72]
When the self-hosted server at home already serves a trusted SSL certificate (_letsencrypt wildcard via dns challenge_), that it's sufficient just to do an SSH tunnel (via systemd) and do some iptables magic on the public VPS.

```
sysctl net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -i eth0 -p tcp -d <PUBLIC_SERVER_IP> --dport 443 -j DNAT --to  127.0.0.1:8443
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```

while the client is just doing

```
ssh -R 8443:localhost:443 root@PUBLIC_SERVER_IP
```

**Comment by adog1314** [comment]
I have been using Iptables with a Wireguard tunnel, it's been rock solid.
https://gist.github.com/adog1314/97bf494d74f56bfff51da9bb4bff8ed0

**Comment by anderspitman** [comment]
@markuman why involve iptables? Can you not just open the SSH tunnel directly to 443? In any case, you are correct that for those who are comfortable with SSH/WireGuard/etc you often don't need a separate tool. This list is more targeted at those who want something a bit simpler/easier to use.
