### ISSUE TITLE
ngrok compile failed go-update.v0?go-get=1: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by cc5zhenhua** [anderspitman/awesome-tunneling#88]
Fetching https://gopkg.in/inconshreveable/go-update.v0?go-get=1
https fetch failed: Get https://gopkg.in/inconshreveable/go-update.v0?go-get=1: x509: certificate has expired or is not yet valid
package gopkg.in/inconshreveable/go-update.v0: unrecognized import path "gopkg.in/inconshreveable/go-update.v0" (https fetch: Get https://gopkg.in/inconshreveable/go-update.v0?go-get=1: x509: certificate has expired or is not yet valid)

**Comment by anderspitman** [comment]
Hi @cc5zhenhua. Not sure what the purpose of this issue is. Can you clarify? Thanks

**Comment by anderspitman** [comment]
Closing for now. Please let me know if I can help at all.
