### ISSUE TITLE
A good software for Expose the Port for Rust

### ISSUE THREAD

**Issue by NameLord** [anderspitman/awesome-tunneling#96]
By Rust i mean a game..
I am trying to host a Rust Server so it can pop-up in the browser and people join my server without having thru RAdmin or Hamachi

**Comment by anderspitman** [comment]
Hey @NameLord. I don't know what protocols the Rust server uses but it's likely based on UDP. So that will probably be the most important constraint. Maybe try frp first.

**Comment by anderspitman** [comment]
Or perhaps https://localtonet.com/ for a hosted option
